Repository OmokNoonE/PPM-backend, pull requests merged in 2024-05, with the labels that each got.

#53 [PR] 공통 코드 관리 기능
  src/main/java/org/omoknoone/ppm/commoncode/aggregate/CommonCode.java
  src/main/java/org/omoknoone/ppm/commoncode/aggregate/CommonCodeGroup.java
  src/main/java/org/omoknoone/ppm/commoncode/dto/CommonCodeDTO.java
  src/main/java/org/omoknoone/ppm/commoncode/dto/CommonCodeGroupDTO.java
  src/main/java/org/omoknoone/ppm/commoncode/repository/CommonCodeGroupRepository.java
  src/main/java/org/omoknoone/ppm/commoncode/repository/CommonCodeRepository.java
  src/main/java/org/omoknoone/ppm/commoncode/service/CommonCodeService.java
  src/main/java/org/omoknoone/ppm/commoncode/service/CommonCodeServiceImpl.java
Labels: backend, feature

#55 [PR] 회원 조회 및 수정 기능 개발
  src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java
  src/main/java/org/omoknoone/ppm/domain/employee/controller/EmployeeController.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/ModifyEmployeeRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/ViewEmployeeResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/repository/EmployeeRepository.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java
  src/test/java/org/omoknoone/ppm/domain/employee/controller/EmployeeControllerTests.java
  src/test/java/org/omoknoone/ppm/domain/employee/dto/ViewEmployeeResponseDTOTest.java
Labels: backend, feature

#56 [PR] 공통 코드 관리 기능 코드 수정 및 예외 처리 코드 추가
  src/main/java/org/omoknoone/ppm/common/exception/GlobalExceptionHandler.java
  src/main/java/org/omoknoone/ppm/commoncode/aggregate/CommonCode.java
  src/main/java/org/omoknoone/ppm/commoncode/dto/CommonCodeGroupResponseDTO.java
  src/main/java/org/omoknoone/ppm/commoncode/dto/CommonCodeResponseDTO.java
  src/main/java/org/omoknoone/ppm/commoncode/repository/CommonCodeRepository.java
  src/main/java/org/omoknoone/ppm/commoncode/service/CommonCodeService.java
  src/main/java/org/omoknoone/ppm/commoncode/service/CommonCodeServiceImpl.java
  src/main/resources/messages.yml
Labels: backend, feature, refactor, rename

#58 [PR] 회원 로그인 및 로그아웃 기능 개발
  src/main/java/org/omoknoone/ppm/PpmApplication.java
  src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Auth.java
  src/main/java/org/omoknoone/ppm/domain/employee/controller/AuthController.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/LoginEmployeeDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/RequestLoginDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/repository/AuthRepository.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/AuthService.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/AuthServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java
  src/main/java/org/omoknoone/ppm/security/AuthenticationFilter.java
  src/main/java/org/omoknoone/ppm/security/CorsConfig.java
  src/main/java/org/omoknoone/ppm/security/JwtFilter.java
  src/main/java/org/omoknoone/ppm/security/JwtTokenProvider.java
  src/main/java/org/omoknoone/ppm/security/JwtUtil.java
  src/main/java/org/omoknoone/ppm/security/Role.java
  src/main/java/org/omoknoone/ppm/security/SessionEmployee.java
  src/main/java/org/omoknoone/ppm/security/WebSecurity.java
Labels: backend, feature

#61 [PR] 회원가입 기능 개발
  src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java
  src/main/java/org/omoknoone/ppm/domain/employee/controller/EmployeeController.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/SignUpEmployeeRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java
Labels: backend, feature

#62 [PR] 토큰 PK 자료형을 UUID로 변경
  src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Auth.java
  src/main/java/org/omoknoone/ppm/domain/employee/controller/AuthController.java
  src/main/java/org/omoknoone/ppm/domain/employee/repository/AuthRepository.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/AuthService.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/AuthServiceImpl.java
  src/main/java/org/omoknoone/ppm/security/AuthenticationFilter.java
  src/main/java/org/omoknoone/ppm/security/JwtFilter.java
  src/main/java/org/omoknoone/ppm/security/JwtUtil.java
Labels: backend, feature, refactor

#64 [PR] 프로젝트 생성, 수정 기능 개발
  src/main/java/org/omoknoone/ppm/domain/project/aggregate/Project.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/CreateProjectRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/ModifyProjectRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectRepository.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
Labels: backend, feature

#65 [PR] 프로젝트 구성원 조회 관리 기능 개발
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/CreateProjectMemberRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ModifyProjectMemberRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/viewProjectMembersByProjectResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
Labels: backend, feature

#66 [PR] 대시보드 그래프 데이터 저장을 위한 mongoDB 도입
  build.gradle
  src/main/java/org/omoknoone/ppm/PpmApplication.java
  src/main/java/org/omoknoone/ppm/projectDashboard/aggregate/ProjectDashboard.java
  src/main/java/org/omoknoone/ppm/projectDashboard/controller/ProjectDashboardController.java
  src/main/java/org/omoknoone/ppm/projectDashboard/dto/ProjectDashboardDTO.java
  src/main/java/org/omoknoone/ppm/projectDashboard/repository/ProjectDashboardRepository.java
  src/main/java/org/omoknoone/ppm/projectDashboard/service/ProjectDashboardService.java
  src/main/java/org/omoknoone/ppm/projectDashboard/service/ProjectDashboardServiceImpl.java
  src/main/java/org/omoknoone/ppm/projectDashboard/vo/ProjectDashboardVO.java
Labels: backend, feature

#68 [PR] 역할 목록 조회 기능
  src/main/java/org/omoknoone/ppm/domain/Role/aggregate/Role.java
  src/main/java/org/omoknoone/ppm/domain/Role/controller/RoleController.java
  src/main/java/org/omoknoone/ppm/domain/Role/dto/ViewRoleListResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/Role/repository/RoleRepository.java
  src/main/java/org/omoknoone/ppm/domain/Role/service/RoleService.java
  src/main/java/org/omoknoone/ppm/domain/Role/service/RoleServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ModifyProjectMemberRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
  src/main/java/org/omoknoone/ppm/security/Role.java
Labels: backend, feature

#69 [PR] 일정 수정 및 삭제와 일정 수정내역 기능 구현
  src/main/java/org/omoknoone/ppm/domain/plpermission/aggregate/PLPermission.java
  src/main/java/org/omoknoone/ppm/domain/schedule/aggregate/Schedule.java
  src/main/java/org/omoknoone/ppm/domain/schedule/aggregate/ScheduleHistory.java
  src/main/java/org/omoknoone/ppm/domain/schedule/aggregate/ScheduleRequirementMap.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleHistoryController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/CreateScheduleDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/CreateScheduleHistoryDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/ModifyScheduleDateDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/ModifyScheduleProgressDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/ModifyScheduleTitleAndContentDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/RequestCreateScheduleHistoryDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/RequestModifyScheduleDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/ScheduleDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/ScheduleHistoryDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleHistoryRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/vo/RequestSchedule.java
  src/main/java/org/omoknoone/ppm/domain/schedule/vo/ResponseSchedule.java
  src/main/java/org/omoknoone/ppm/domain/schedule/vo/ResponseScheduleHistory.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/aggregate/Stakeholders.java
  src/main/java/org/omoknoone/ppm/domain/task/aggregate/Task.java
  src/main/java/org/omoknoone/ppm/schedule/service/ScheduleService.java
Labels: backend, feature

#70 [PR] 업무 기능 구현
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/task/aggregate/Task.java
  src/main/java/org/omoknoone/ppm/domain/task/controller/TaskController.java
  src/main/java/org/omoknoone/ppm/domain/task/dto/CreateTaskDTO.java
  src/main/java/org/omoknoone/ppm/domain/task/dto/ModifyTaskDTO.java
  src/main/java/org/omoknoone/ppm/domain/task/dto/RequestCreateTaskDTO.java
  src/main/java/org/omoknoone/ppm/domain/task/dto/RequestModifyTaskDTO.java
  src/main/java/org/omoknoone/ppm/domain/task/dto/TaskDTO.java
  src/main/java/org/omoknoone/ppm/domain/task/repository/TaskRepository.java
  src/main/java/org/omoknoone/ppm/domain/task/service/TaskService.java
  src/main/java/org/omoknoone/ppm/domain/task/service/TaskServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/task/vo/ResponseTask.java
Labels: backend, feature

#72 [PR] 이해관계자 기능 구현
  src/main/java/org/omoknoone/ppm/domain/stakeholders/aggregate/Stakeholders.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/controller/StakeholdersController.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/CreateStakeholdersDTO.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/ModifyStakeholdersDTO.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/RequestCreateStakeholdersDTO.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/RequestModifyStakeholdersDTO.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/StakeholdersDTO.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/repository/StakeholdersRepository.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersService.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/vo/ResponseStakeholders.java
Labels: backend, feature

#75 [PR] 프로젝트 구성원 죄외(soft delete), 재활성화 기능 구현, 수정 기능 변수명 일부 수정
  src/main/java/org/omoknoone/ppm/common/ResponseMessage.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
Labels: backend, feature, refactor

#74 [PR]요구사항 등록, 수정, 삭제(soft delete) 기능 구현
  src/main/java/org/omoknoone/ppm/domain/requirements/aggregate/Requirements.java
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java
  src/main/java/org/omoknoone/ppm/domain/requirements/dto/RequirementsDTO.java
  src/main/java/org/omoknoone/ppm/domain/requirements/repository/RequirementsRepository.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsService.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/requirements/vo/RequestModifyRequirement.java
  src/main/java/org/omoknoone/ppm/domain/requirements/vo/RequestRequirement.java
  src/main/java/org/omoknoone/ppm/domain/requirements/vo/ResponseRequirement.java
Labels: backend, feature

#76 [PR] 대시보드 그래프 데이터 업데이트 기능 구현
  src/main/java/org/omoknoone/ppm/projectDashboard/aggregate/ProjectDashboard.java
  src/main/java/org/omoknoone/ppm/projectDashboard/controller/ProjectDashboardController.java
  src/main/java/org/omoknoone/ppm/projectDashboard/dto/ProjectDashboardDTO.java
  src/main/java/org/omoknoone/ppm/projectDashboard/repository/ProjectDashboardRepository.java
  src/main/java/org/omoknoone/ppm/projectDashboard/service/ProjectDashboardService.java
  src/main/java/org/omoknoone/ppm/projectDashboard/service/ProjectDashboardServiceImpl.java
Labels: backend, feature, refactor

#80 [PR] Hotfix/general hotfix2
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/controller/ProjectDashboardController.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/dto/ProjectDashboardDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/ProjectDashboardService.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/ProjectDashboardServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/vo/ProjectDashboardVO.java
  src/main/java/org/omoknoone/ppm/domain/requirements/aggregate/Requirements.java
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsService.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java
  src/main/java/org/omoknoone/ppm/projectDashboard/dto/ProjectDashboardDTO.java
Labels: backend, refactor

#85 [PR] collection/table명 중복에 따라 이름 변경
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/aggregate/Graph.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/controller/GraphController.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/dto/GraphDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/repository/GraphRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphService.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
Labels: rename

#82 [PR]프로젝트 ID를 통한 요구사항 목록 조회, 프로젝트 ID 및 요구사항 ID를 통한 요구사항 조회 기능
  src/main/java/org/omoknoone/ppm/domain/requirements/aggregate/Requirements.java
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java
  src/main/java/org/omoknoone/ppm/domain/requirements/dto/RequirementsDTO.java
  src/main/java/org/omoknoone/ppm/domain/requirements/dto/RequirementsListByProjectDTO.java
  src/main/java/org/omoknoone/ppm/domain/requirements/repository/RequirementsRepository.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsService.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/requirements/vo/ResponseRequirementsListByProject.java
Labels: backend, feature

#83 [PR] ScheduleTitle을 통한 일정 검색 기능 구현
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/SearchScheduleListDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/vo/ResponseSearchScheduleList.java
Labels: backend, feature

#86 [PR]요구사항 수정내역 등록 기능 구현
  src/main/java/org/omoknoone/ppm/domain/requirements/aggregate/RequirementsHistory.java
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsHistoryController.java
  src/main/java/org/omoknoone/ppm/domain/requirements/dto/RequirementsHistoryDTO.java
  src/main/java/org/omoknoone/ppm/domain/requirements/repository/RequirementsHistoryRepository.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsHistoryService.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsHistoryServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/requirements/vo/RequestCreateRequirementsHistory.java
  src/main/java/org/omoknoone/ppm/domain/requirements/vo/ResponseRequirementHistory.java
Labels: backend, feature

#87 [PR] 대시보드 그래프 데이터 update에 필요한 data 조회 기능 개발-1
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/controller/GraphController.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/UpdateDataDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/UpdateTableDataDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: backend, feature

#90 [PR] 일정 요구사항 맵 기능 구현
  src/main/java/org/omoknoone/ppm/domain/schedule/aggregate/ScheduleRequirementMap.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleRequirementMapController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/CreateScheduleRequirementMapDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/RequestCreateScheduleRequirementMapDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/ScheduleRequirementMapDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRequirementMapRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleRequirementMapService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleRequirementMapServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/vo/ResponseScheduleHistory.java
  src/main/java/org/omoknoone/ppm/domain/schedule/vo/ResponseScheduleRequirementMap.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersServiceImpl.java
Labels: backend, feature

#93 [PR] Role 도메인 삭제
  src/main/java/org/omoknoone/ppm/domain/role/aggregate/Role.java
  src/main/java/org/omoknoone/ppm/domain/role/controller/RoleController.java
  src/main/java/org/omoknoone/ppm/domain/role/dto/ViewRoleListResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/role/repository/RoleRepository.java
  src/main/java/org/omoknoone/ppm/domain/role/service/RoleService.java
  src/main/java/org/omoknoone/ppm/domain/role/service/RoleServiceImpl.java
Labels: backend, remove

#94 [PR] PL권한 이름 변경 (-> 권한)
  src/main/java/org/omoknoone/ppm/domain/permission/aggregate/Permission.java
  src/main/java/org/omoknoone/ppm/domain/permission/controller/PermissionController.java
  src/main/java/org/omoknoone/ppm/domain/permission/dto/CreatePermissionDTO.java
  src/main/java/org/omoknoone/ppm/domain/permission/dto/PermissionDTO.java
  src/main/java/org/omoknoone/ppm/domain/permission/dto/RequestCreatePermissionDTO.java
  src/main/java/org/omoknoone/ppm/domain/permission/repository/PermissionRepository.java
  src/main/java/org/omoknoone/ppm/domain/permission/service/PermissionService.java
  src/main/java/org/omoknoone/ppm/domain/permission/service/PermissionServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/permission/vo/ResponsePermission.java
  src/main/java/org/omoknoone/ppm/domain/plpermission/aggregate/PLPermission.java
  src/main/java/org/omoknoone/ppm/domain/plpermission/controller/PLPermissionController.java
  src/main/java/org/omoknoone/ppm/domain/plpermission/dto/CreatePLPermissionDTO.java
  src/main/java/org/omoknoone/ppm/domain/plpermission/dto/PLPermissionDTO.java
  src/main/java/org/omoknoone/ppm/domain/plpermission/dto/RequestCreatePLPermissionDTO.java
  src/main/java/org/omoknoone/ppm/domain/plpermission/repository/PLPermissionRepository.java
  src/main/java/org/omoknoone/ppm/domain/plpermission/service/PLPermissionService.java
  src/main/java/org/omoknoone/ppm/domain/plpermission/service/PLPermissionServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/plpermission/vo/ResponsePLPermission.java
Labels: backend, fix, rename

#98 [PR} 휴일 추가 기능
  src/main/java/org/omoknoone/ppm/config/RestTemplateConfig.java
  src/main/java/org/omoknoone/ppm/domain/holiday/HolidayControllerTest.java
  src/main/java/org/omoknoone/ppm/domain/holiday/aggregate/Holiday.java
  src/main/java/org/omoknoone/ppm/domain/holiday/dto/CreateHolidayDTO.java
  src/main/java/org/omoknoone/ppm/domain/holiday/dto/HolidayDTO.java
  src/main/java/org/omoknoone/ppm/domain/holiday/repository/HolidayRepository.java
  src/main/java/org/omoknoone/ppm/domain/holiday/service/HolidayService.java
  src/main/java/org/omoknoone/ppm/domain/holiday/service/HolidayServiceImpl.java
Labels: backend, feature, planning

#99 [PR] 프로젝트 수정, 수정 내역 기록, 수정 내역 조회 기능 구현
  src/main/java/org/omoknoone/ppm/domain/project/aggregate/Project.java
  src/main/java/org/omoknoone/ppm/domain/project/aggregate/ProjectHistory.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectHistoryController.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/ModifyProjectHistoryDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/ModifyProjectRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/ProjectHistoryDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectHistoryRepository.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectHistoryService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectHistoryServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/project/vo/ResponseProjectHistory.java
Labels: backend, feature

#103 [PR] 공수 계산 기능 구현
  src/main/java/org/omoknoone/ppm/domain/holiday/repository/HolidayRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/ModifyScheduleDateDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: backend, feature

#104 [PR] 접근 권한 확인용 AOP 구현
  src/main/java/org/omoknoone/ppm/common/annotation/Permission.java
  src/main/java/org/omoknoone/ppm/common/aop/AuthorizationAspect.java
  src/main/java/org/omoknoone/ppm/domain/commoncode/repository/CommonCodeGroupRepository.java
  src/main/java/org/omoknoone/ppm/domain/commoncode/repository/CommonCodeRepository.java
  src/main/java/org/omoknoone/ppm/domain/commoncode/service/CommonCodeService.java
  src/main/java/org/omoknoone/ppm/domain/commoncode/service/CommonCodeServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: feature

#106 [PR] 비밀번호 수정 기능 개발
  src/main/java/org/omoknoone/ppm/domain/employee/controller/EmployeeController.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/ModifyPasswordRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/exception/PasswordMismatchException.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java
Labels: feature

#107 [PR] Log 파일로 저장하기
  src/main/resources/logback.xml
Labels: feature

#109 [PR] 날짜 설정 범위에 따른 일정목록 조회(필터링) 기능 구현
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: backend, feature

#111 [PR] 프로젝트 복사 기능 구현
  src/main/java/org/omoknoone/ppm/domain/project/aggregate/Project.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/ModifyProjectHistoryDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/ModifyProjectRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/aggregate/Schedule.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: feature

#113 [PR] employeeName을 통한 사원 검색 기능 구현
  src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java
  src/main/java/org/omoknoone/ppm/domain/employee/controller/EmployeeController.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/ViewEmployeeResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/repository/EmployeeRepository.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java
Labels: backend, feature

#115 [PR] 해당 일자가 포함된 주에 끝나야할 일정 목록 조회 기능 구현
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: backend, feature

#119 [PR]코드오류수정
  src/main/java/org/omoknoone/ppm/domain/employee/controller/EmployeeController.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java
Labels: fix

#118 [PR] 수정내역 관리 기능 개발
  src/main/java/org/omoknoone/ppm/common/annotation/NoLogIfDraft.java
  src/main/java/org/omoknoone/ppm/common/aop/EntityModificationAspect.java
  src/main/java/org/omoknoone/ppm/common/enums/RecordingTarget.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMemberHistory.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ModifyProjectMemberRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberHistoryRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsHistoryController.java
  src/main/java/org/omoknoone/ppm/domain/requirements/dto/ModifyRequirementRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsHistoryService.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsHistoryServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsService.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleHistoryController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/RequestModifyScheduleDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: feature

#120 [PR] 대시보드 그래프 init 및 line graph update 기능 구현
  src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java
  src/main/java/org/omoknoone/ppm/domain/employee/repository/EmployeeRepository.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/CreateProjectRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/aggregate/Graph.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/aggregate/ProjectDashboard.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/controller/GraphController.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/dto/GraphDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/repository/GraphRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphService.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/ProjectDashboardService.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/ProjectDashboardServiceImpl.java
Labels: backend, feature

#122 [PR] [hotfix] Vue프로젝트 CORS 충돌 해결
  src/main/java/org/omoknoone/ppm/config/WebConfig.java
  src/main/java/org/omoknoone/ppm/security/CorsConfig.java
Labels: fix

#123 [PR] graph update 부분 수정
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphService.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: fix

#127 [PR] 컨트롤러 반환 형태 ResponseMessage 클래스 사용으로 변경
  src/main/java/org/omoknoone/ppm/common/HttpHeadersCreator.java
  src/main/java/org/omoknoone/ppm/domain/employee/controller/EmployeeController.java
  src/main/java/org/omoknoone/ppm/domain/notification/controller/NotificationController.java
  src/main/java/org/omoknoone/ppm/domain/notification/controller/NotificationSettingController.java
  src/main/java/org/omoknoone/ppm/domain/permission/controller/PermissionController.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectHistoryController.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/controller/GraphController.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/controller/ProjectDashboardController.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsHistoryController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleHistoryController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleRequirementMapController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/controller/StakeholdersController.java
  src/main/java/org/omoknoone/ppm/domain/task/controller/TaskController.java
Labels: refactor

#128 [PR] 매일 오후 12시에 상태가 착수인 프로젝트들의 그래프 데이터 업데이트
  src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectRepository.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphScheduler.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphService.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
Labels: backend, feature

#131 [PR] 차주에 끝나야할 일정조회 및 금주, 차주 완료 일정 비율 계산 기능
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java
  src/main/java/org/omoknoone/ppm/domain/requirements/dto/RequirementsListByProjectDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceCalculator.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: backend, feature

#132 [PR] 그래프 관련 로직 수정
  src/main/java/org/omoknoone/ppm/domain/project/aggregate/Project.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/project/vo/ProjectModificationResult.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/aop/GraphAspect.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphService.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
Labels: backend, feature, fix

#134 [PR] Gauge Graph 데이터 업데이트 형식 수정
  src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphService.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/UpdateDataDTO.java
Labels: fix

#133 [PR] 구간별 예상 누적 진행률 기능 구현 및 코드 일부 수정
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceCalculator.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: backend, feature

#136 [PR] 프로젝트 목록 및 상세 조회 기능 개발
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/ViewProjectResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectRepository.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
  src/test/resources/ProjectTest.http
Labels: feature

#137 [PR] 구간별 누적 비율 계산 코드 수정 및 요구사항 관련 코드 수정
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java
  src/main/java/org/omoknoone/ppm/domain/requirements/repository/RequirementsRepository.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsService.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: backend, feature

#138 [PR] 프로젝트 생성 기능 로직에 맞게 구현
  src/main/java/org/omoknoone/ppm/domain/commoncode/repository/CommonCodeRepository.java
  src/main/java/org/omoknoone/ppm/domain/commoncode/service/CommonCodeService.java
  src/main/java/org/omoknoone/ppm/domain/commoncode/service/CommonCodeServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/project/aggregate/Project.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/CreateProjectRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/CreateProjectMemberRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: feature

#139 [PR] 프로젝트 목록 ID 기준으로 내림차순
  src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectRepository.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
Labels: feature

#144 [PR] Graph Delete기능 구현
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/controller/GraphController.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphService.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
Labels: backend, feature

#145 [PR] .http파일 추가 및 코드 수정사항
  src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/SignUpEmployeeRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/permission/controller/PermissionController.java
  src/main/java/org/omoknoone/ppm/domain/permission/dto/RequestCreatePermissionDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/CreateProjectMemberRequestDTO.java
  src/test/resources/api/tests/EmployeeTest.http
  src/test/resources/api/tests/NotificationTest.http
  src/test/resources/api/tests/PermissionTest.http
  src/test/resources/api/tests/ProjectMemberTest.http
  src/test/resources/api/tests/ProjectTest.http
  src/test/resources/api/tests/ProjectdashboardTest.http
  src/test/resources/api/tests/RequirementsTest.http
  src/test/resources/api/tests/ScheduleTest.http
  src/test/resources/api/tests/StakeholdersTest.http
  src/test/resources/api/tests/TaskTest.http
Labels: backend, test

#148 [PR] Dockerfile 추가
  .gitignore
  Dockerfile
Labels: devops

#149 [PR] jasypt추가
  Dockerfile
  build.gradle
  src/main/java/org/omoknoone/ppm/config/JasyptConfig.java
  src/main/java/org/omoknoone/ppm/projectDashboard/controller/ProjectDashboardController.java
  src/main/java/org/omoknoone/ppm/projectDashboard/service/ProjectDashboardServiceImpl.java
  src/main/resources/application.yml
Labels: devops

#147 [PR] 금주 및 차주 일정 조회 코드 수정
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/ScheduleDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceCalculator.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: backend, feature

#151 [PR] 회원(Auth, Employee) 관련 테스트 코드 작성
  src/main/java/org/omoknoone/ppm/domain/employee/dto/SignUpEmployeeRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/CreateProjectMemberRequestDTO.java
  src/test/java/org/omoknoone/ppm/domain/employee/service/AuthServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceTests.java
Labels: test

#153 [PR] Front Schedule Sheet에 사용할 일정 조회 기능
  src/main/java/org/omoknoone/ppm/domain/permission/dto/RoleAndSchedulesDTO.java
  src/main/java/org/omoknoone/ppm/domain/permission/repository/PermissionRepository.java
  src/main/java/org/omoknoone/ppm/domain/permission/service/PermissionService.java
  src/main/java/org/omoknoone/ppm/domain/permission/service/PermissionServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/ScheduleSheetDataDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/vo/ResponseScheduleSheetData.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/StakeholdersEmployeeInfoDTO.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/repository/StakeholdersRepository.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersService.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersServiceImpl.java
Labels: backend, feature

#155 [PR] Hotfix/schedule sheetdata merge error resolve
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: backend, fix

#156 [PR] 프로젝트(Project) 테스트 코드 작성
  src/main/java/org/omoknoone/ppm/domain/project/dto/CreateProjectRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/ModifyProjectHistoryDTO.java
  src/test/java/org/omoknoone/ppm/domain/project/service/ProjectServiceTest.java
Labels: test

#159 [PR] 일정 도메인 테스트 코드 작성
  src/main/java/org/omoknoone/ppm/domain/schedule/aggregate/Schedule.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/RequestModifyScheduleDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
  src/test/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryServiceTests.java
  src/test/java/org/omoknoone/ppm/domain/schedule/service/ScheduleRequirementMapServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceTests.java
Labels: test

#161 [PR] 요구사항 도메인의 서비스 테스트 코드 작성
  src/main/java/org/omoknoone/ppm/domain/requirements/dto/ModifyRequirementRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/requirements/dto/RequirementsHistoryDTO.java
  src/test/java/org/omoknoone/ppm/domain/requirements/service/RequirementsHistoryServiceTests.java
  src/test/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceTests.java
Labels: test

#163 [fix] ProjectMemberCreatedDate 데이터 형 변환 및 TODO 추가
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/RequestCreateScheduleRequirementMapDTO.java
  src/main/java/org/omoknoone/ppm/domain/task/controller/TaskController.java
Labels: backend, bug

#165 [PR] 프로젝트 구성원 추가 그리고 제외 및 내역 관리 기능 개선
  src/main/java/org/omoknoone/ppm/domain/employee/dto/ViewEmployeeResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/repository/EmployeeRepository.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMemberHistory.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/CreateProjectMemberHistoryRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/CreateProjectMemberRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ModifyProjectMemberRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ViewAvailableMembersResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ViewProjectMembersByProjectResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/viewProjectMembersByProjectResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberHistoryRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
Labels: backend, feature, refactor

#168 [PR] 프로젝트 구성원 기능 추가
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/CreateProjectMemberRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ModifyProjectMemberRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
  src/test/resources/api/tests/ProjectMemberTest.http
  src/test/resources/api/tests/ProjectTest.http
Labels: backend, feature
