Repository OmokNoonE/PPM-backend, pull requests merged in 2024-06, with the labels that each got.

#169 [PR] notification package에서 websocket 관련 코드 삭제 및 일부 코드 수정
  src/main/java/org/omoknoone/ppm/domain/notification/aggregate/entity/NotificationSetting.java
  src/main/java/org/omoknoone/ppm/domain/notification/aggregate/entity/NotificationSettings.java
  src/main/java/org/omoknoone/ppm/domain/notification/aggregate/entity/Sent.java
  src/main/java/org/omoknoone/ppm/domain/notification/controller/NotificationSettingsController.java
  src/main/java/org/omoknoone/ppm/domain/notification/dto/NotificationSettingsRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/notification/dto/NotificationSettingsResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/notification/repository/NotificationSettingRepository.java
  src/main/java/org/omoknoone/ppm/domain/notification/repository/NotificationSettingsRepository.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationScheduler.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationService.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationSettingService.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationSettingServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationSettingsService.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationSettingsServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/strategy/EmailNotificationStrategy.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/strategy/NotificationStrategy.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/strategy/SlackNotificationStrategy.java
  src/main/java/org/omoknoone/ppm/domain/permission/dto/PermissionDTO.java
  src/main/java/org/omoknoone/ppm/domain/permission/repository/PermissionRepository.java
  src/main/java/org/omoknoone/ppm/domain/permission/service/PermissionServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceCalculator.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/aggregate/Stakeholders.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/StakeholdersDTO.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/repository/StakeholdersRepository.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersServiceImpl.java
Labels: backend, refactor

#171 [PR] 일정 이해관계자, 수정내역 조회 시, 이름, 사원번호, 역할 조회 기능 구현
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleHistoryController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/ViewScheduleHistoryDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleHistoryRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/vo/ResponseViewScheduleHistory.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/controller/StakeholdersController.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/ViewStakeholdersDTO.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/repository/StakeholdersRepository.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersService.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/vo/ResponseViewStakeholders.java
  src/test/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryServiceTests.java
Labels: backend, fix

#172 [PR] 금주, 차주 일정 조회 기능
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/FindSchedulesForWeekDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceCalculator.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/StakeholdersEmployeeInfoDTO.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/repository/StakeholdersRepository.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersServiceImpl.java
Labels: feature, fix

#173 [PR] 병합 후, 오류 수정 PR
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/permission/repository/PermissionRepository.java
  src/main/java/org/omoknoone/ppm/domain/permission/service/PermissionServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ProjectMemberDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersServiceImpl.java
Labels: backend, bug, feature, fix

#177 [PR] 프로젝트 구성원 http 테스트 셋업
  src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
  src/test/resources/api/tests/ProjectMemberTest.http
Labels: backend, test

#176 [PR] 병합 후, 오류 수정 및 일정 시트 조회 기능 수정
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/RoleAndScheduleIdList.java
Labels: backend, bug, fix

#180 [fix] 잘못된 코드 해결
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/permission/service/PermissionService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersService.java
Labels: backend, fix

#181 [PR] 조회, 생성, 수정 부분 오류 및 클라이언트에 보여줘야 하는 값으로 변경
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ViewProjectMembersByProjectResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
  src/test/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceTests.java
Labels: fix

#182 [PR] calculateScheduleRatios 메소드 projectId 값을 받아오도록 수정
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: backend, fix

#184 [PR] 구간별 예상 진행률 계산 시 projectId 반영되도록 수정
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: backend, fix

#185 [PR] notificadtion 코드 수정 MariaDB에서 read가 예약어로 활용 되어 markAsRead로 일괄 수정
  src/main/java/org/omoknoone/ppm/domain/notification/aggregate/entity/Notification.java
  src/main/java/org/omoknoone/ppm/domain/notification/controller/NotificationController.java
  src/main/java/org/omoknoone/ppm/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationService.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
  src/test/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceTest.java
Labels: backend, bug, fix, refactor

#186 [PR] 그래프 데이터 관련 수정
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
Labels: backend, fix

#187 [PR] 로그인 성공 시, header에 정보 추가
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
  src/main/java/org/omoknoone/ppm/security/AuthenticationFilter.java
  src/main/java/org/omoknoone/ppm/security/CorsConfig.java
  src/main/java/org/omoknoone/ppm/security/WebSecurity.java
Labels: feature

#189 [PR] 변경된 DB에 맞게 알림 코드 수정, 알림 삭제 기능 구현
  src/main/java/org/omoknoone/ppm/domain/notification/controller/NotificationController.java
  src/main/java/org/omoknoone/ppm/domain/notification/repository/NotificationRepository.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationScheduler.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationService.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
Labels: backend, fix

#190 [PR] 각종 오류 수정 및 http 실행 테스트
  src/main/java/org/omoknoone/ppm/common/aop/SentAspect.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/ViewEmployeeResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/notification/aggregate/entity/Notification.java
  src/main/java/org/omoknoone/ppm/domain/notification/controller/NotificationController.java
  src/main/java/org/omoknoone/ppm/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/notification/repository/NotificationRepository.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationScheduler.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationService.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/SentServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/project/aggregate/Project.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/CreateProjectRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMemberHistory.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ProjectMemberHistoryDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ViewProjectMembersByProjectResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberHistoryRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/aggregate/Schedule.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/ViewScheduleHistoryDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleHistoryRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/ViewStakeholdersDTO.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/repository/StakeholdersRepository.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersService.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersServiceImpl.java
  src/main/java/org/omoknoone/ppm/security/AuthenticationFilter.java
  src/main/java/org/omoknoone/ppm/security/CorsConfig.java
  src/main/java/org/omoknoone/ppm/security/WebSecurity.java
  src/test/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceSentNotificationTest.java
  src/test/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceTests.java
  src/test/resources/api/tests/EmployeeTest.http
  src/test/resources/api/tests/ProjectHistoryTest.http
  src/test/resources/api/tests/ProjectMemberTest.http
  src/test/resources/api/tests/ProjectTest.http
  src/test/resources/api/tests/ProjectdashboardTest.http
  src/test/resources/api/tests/RequirementHistoryTest.http
  src/test/resources/api/tests/RequirementsTest.http
  src/test/resources/api/tests/ScheduleHistoryTest.http
  src/test/resources/api/tests/ScheduleRequirementMapTest.http
  src/test/resources/api/tests/ScheduleTest.http
  src/test/resources/api/tests/TaskTest.http
Labels: backend, bug, feature, fix

#193 [PR] line graph update 로직 수정
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
Labels: backend, fix

#194 [PR] 최신 10개의 알림만 화면에 나오도록 코드 수정
  src/main/java/org/omoknoone/ppm/domain/notification/repository/NotificationRepository.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
Labels: backend

#195 [PR] 1차 QA 완료
  src/main/java/org/omoknoone/ppm/domain/notification/repository/NotificationRepository.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/project/aggregate/Project.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/RemoveProjectRequestDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/ViewProjectResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectRepository.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ViewProjectMemberByProjectIdResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/aggregate/Schedule.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleHistoryController.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/ConnectScheduleDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/CreateScheduleDTO.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRequirementMapRepository.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleRequirementMapServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/vo/RequestSchedule.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/repository/StakeholdersRepository.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/vo/ResponseViewStakeholders.java
  src/main/java/org/omoknoone/ppm/domain/task/repository/TaskRepository.java
  src/main/java/org/omoknoone/ppm/domain/task/service/TaskServiceImpl.java
  src/main/java/org/omoknoone/ppm/security/AuthenticationFilter.java
  src/main/java/org/omoknoone/ppm/security/CorsConfig.java
  src/main/java/org/omoknoone/ppm/security/WebSecurity.java
  src/test/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceTests.java
Labels: backend, feature, fix, refactor, rename, test

#197 [PR] testCode 작성
  src/test/java/org/omoknoone/ppm/domain/commoncode/service/CommonCodeServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/holiday/service/HolidayServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/notification/service/NotificationSettingsServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/notification/service/SentServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/project/service/ProjectHistoryServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/projectDashboard/service/ProjectDashboardServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/task/service/TaskServiceTest.java
Labels: test

#202 [Hotfix] Test 오류 임시 수정
  src/main/java/org/omoknoone/ppm/domain/task/dto/ModifyTaskDTO.java
  src/test/java/org/omoknoone/ppm/domain/holiday/service/HolidayServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/projectdashboard/service/GraphServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/projectdashboard/service/ProjectDashboardServiceTest.java
Labels: fix

#204 [HotFix] CORS 추가
  src/main/java/org/omoknoone/ppm/config/WebConfig.java
  src/main/java/org/omoknoone/ppm/security/CorsConfig.java
Labels: fix

#205 [fix] CORS에 WWW추가
  src/main/java/org/omoknoone/ppm/config/WebConfig.java
  src/main/java/org/omoknoone/ppm/security/CorsConfig.java
Labels: fix

#211 [PR] 테스트코드 수정한 부분까지 PR입니다.
  src/test/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceTests.java
  src/test/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/notification/service/NotificationSettingsServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/notification/service/SentServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/project/service/ProjectHistoryServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/project/service/ProjectServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/requirements/service/RequirementsHistoryServiceTests.java
  src/test/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceTests.java
  src/test/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceTests.java
Labels: test

#214 [PR] 관리자용 회원 관리, 프로젝트 관리 기능 구현
  src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java
  src/main/java/org/omoknoone/ppm/domain/employee/controller/EmployeeController.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/AuthDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/LoginEmployeeDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/ViewEmployeeListResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/repository/AuthRepository.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/AuthService.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/AuthServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectHistoryController.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/ProjectHistoryDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/ViewAllProjectResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectHistoryServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/project/vo/ResponseProjectHistory.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ProjectMemberEmployeeDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
  src/main/java/org/omoknoone/ppm/security/AuthenticationFilter.java
  src/main/java/org/omoknoone/ppm/security/CorsConfig.java
  src/main/java/org/omoknoone/ppm/security/WebSecurity.java
  src/test/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceTests.java
  src/test/java/org/omoknoone/ppm/domain/project/service/ProjectServiceTest.java
  src/test/resources/api/tests/EmployeeTest.http
Labels: DB, feature, rename, test

#215 [PR] 프로젝트 목록 조회 시 isDeleted 추가
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
Labels: refactor

#216 [feature] 알림 전송 기능 수정 및 기능 개발
  src/main/java/org/omoknoone/ppm/domain/notification/service/CheckNotificationService.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/CheckNotificationServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationScheduler.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationService.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectRepository.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
Labels: backend, feature, fix

#217 [PR] notificationController 수정
  src/main/java/org/omoknoone/ppm/domain/notification/controller/NotificationController.java
Labels: backend, fix

#218 [PR] 이해관계자 중 담당자에 따른 알림 생성 기능 구현
  src/main/java/org/omoknoone/ppm/domain/notification/service/CheckNotificationServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationScheduler.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/strategy/EmailNotificationStrategy.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/FindSchedulesForWeekDTO.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/repository/StakeholdersRepository.java
Labels: backend, feature

#219 [PR] NotificationTemplate 수정
  src/main/java/org/omoknoone/ppm/domain/notification/aggregate/entity/NotificationSettings.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
Labels: backend, fix

#220 [Release] PPM back v.1.0.9
  src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java
  src/main/java/org/omoknoone/ppm/domain/employee/controller/EmployeeController.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/AuthDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/LoginEmployeeDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/dto/ViewEmployeeListResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/employee/repository/AuthRepository.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/AuthService.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/AuthServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java
  src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/notification/aggregate/entity/NotificationSettings.java
  src/main/java/org/omoknoone/ppm/domain/notification/controller/NotificationController.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/CheckNotificationService.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/CheckNotificationServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationScheduler.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationService.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/notification/service/strategy/EmailNotificationStrategy.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java
  src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectHistoryController.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/ProjectHistoryDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/dto/ViewAllProjectResponseDTO.java
  src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectRepository.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectHistoryServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java
  src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/project/vo/ResponseProjectHistory.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ProjectMemberEmployeeDTO.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/dto/FindSchedulesForWeekDTO.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/repository/StakeholdersRepository.java
  src/main/java/org/omoknoone/ppm/security/AuthenticationFilter.java
  src/main/java/org/omoknoone/ppm/security/CorsConfig.java
  src/main/java/org/omoknoone/ppm/security/WebSecurity.java
  src/test/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceTests.java
  src/test/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/notification/service/NotificationSettingsServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/notification/service/SentServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/project/service/ProjectHistoryServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/project/service/ProjectServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceTest.java
  src/test/java/org/omoknoone/ppm/domain/requirements/service/RequirementsHistoryServiceTests.java
  src/test/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceTests.java
  src/test/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceTests.java
  src/test/resources/api/tests/EmployeeTest.http
Labels: backend, bug, feature, refactor, style, test

#221 [PR] 프로젝트 구성원 추가 리스트에서 admin 계정은 목록에 추가 되지 않도록 수정
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
Labels: backend, refactor

#222 [Release] PPM back v.1.1.0
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
Labels: backend, refactor

#224 [Release] PPM Back v.1.1.1
  src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java
Labels: fix

#227 [PR] 서버 시간 한국시간으로 설정하기
  src/main/java/org/omoknoone/ppm/PpmApplication.java
  src/main/java/org/omoknoone/ppm/config/TimeZoneConfig.java
Labels: feature, fix

#228 [Release] PPM Back v.1.1.2
  src/main/java/org/omoknoone/ppm/PpmApplication.java
  src/main/java/org/omoknoone/ppm/config/TimeZoneConfig.java
Labels: backend, fix

#233 [PR] 홈서버 이전에 따른 설정 변경
  src/main/java/org/omoknoone/ppm/config/WebConfig.java
  src/main/java/org/omoknoone/ppm/security/CorsConfig.java
  src/main/resources/application.yml
Labels: devops, feature

#236 [refactor] 프로젝트 구성원 기능 일부 개선 및 aggregate 수정
  src/main/java/org/omoknoone/ppm/PpmApplication.java
  src/main/java/org/omoknoone/ppm/domain/employee/repository/EmployeeRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMemberHistory.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryService.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
Labels: backend, refactor

#237 [Refactor] 요구사항에서 Entity로 작성된 부분을 DTO로 변경
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java
  src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsHistoryController.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsService.java
  src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleRequirementMapService.java
  src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java
  src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersService.java
  src/main/java/org/omoknoone/ppm/domain/task/service/TaskService.java
Labels: backend, refactor

#240 [Refactor] Controller 응답 형태 간결화 및 Restful URL 적용
  src/main/java/org/omoknoone/ppm/common/ResponseMessage.java
  src/main/java/org/omoknoone/ppm/common/ResponseUtil.java
  src/main/java/org/omoknoone/ppm/common/exception/ExceptionInfo.java
  src/main/java/org/omoknoone/ppm/common/exception/ExceptionMapper.java
  src/main/java/org/omoknoone/ppm/common/exception/GlobalExceptionHandler.java
  src/main/java/org/omoknoone/ppm/domain/employee/controller/EmployeeController.java
Labels: refactor
